### ISSUE TITLE
Some questions about the ground truth informaiton

### ISSUE THREAD

**Issue by HelloWorldLTY** [Vivianstats/scLink#7]
Hi, sorry to disturb you. I wonder for the ground truth information about gene coexpression networks, do you have any ideas about how to find these data? I think according to your paper, only simulation data can be used as the ground truth information. Am I correct? Thanks a lot.

**Comment by Vivianstats** [comment]
Hello,

To the best of my knowledge, there does not exist genome-wide ground truth information about gene coexpression networks in real data. There might be data that come with very limited experimental validations. Sometimes people also use protein-protein interactions as a reference.

Best,
Vivian

**Comment by HelloWorldLTY** [comment]
Got it, thanks a lot!
