### ISSUE TITLE
Some questions about simulation process

### ISSUE THREAD

**Issue by HelloWorldLTY** [Vivianstats/scLink#8]
Hi, I wonder how to generate a simulation process based on the description you have in the paper. In the method part, you state that you first generate a correlation matrix and then transfer it into an adjacency matrix based on uniform distribution. Therefore, why this adjacency matrix is not the final edge matrix of the graph? Since it seems that you mentioned the distribution of edges follows some rules:
![image](https://user-images.githubusercontent.com/43333475/197364645-8e1fa37f-6ffb-4643-889b-79d48678b9cf.png)
Do the statements conflict? Thanks.

**Comment by Vivianstats** [comment]
Hi, just to clarify, we first generated a connectivity matrix and then generated a partial correlation matrix based on the connectivity matrix.

**Comment by HelloWorldLTY** [comment]
Hi, many thanks for your reply!

**Comment by HelloWorldLTY** [comment]
Hi, I meet a new problem when I intend to simulate the hub datasets:
![image](https://user-images.githubusercontent.com/43333475/198446644-e6c62f89-41d6-425a-8da8-8a0038557894.png)
I try to control the ncluster>degree.hubs, but still, receive this error. Could you please help me solve it? Thanks a lot.

**Comment by Vivianstats** [comment]
This is an internal error from the ldstatsHD package, so I would suggest that you reach out to the developer of this package for this question.

**Comment by HelloWorldLTY** [comment]
Thanks a lot!. Btw, I also found a warning when I normalized data for sume datasets then run the sclink:
Warning: the standard deviation is zeroConstructing gene networks ...

If I encounter this error, even if I try to infer co-expression relation from the same tissues, the results are different. Is it the problem of my own dataset? Thanks a lot.
